#!/usr/bin/env python3
"""
scripts/lite/sync-kernel.py
Dynamically generates CLAUDE.md, AGENTS.md, and GEMINI.md from kernel files
to eliminate duplication, drift, and ensure boot context remains under 7k tokens.

AUDIT.md and POLICY.md are included in the sync set so the generated boot
files carry the full contract (VERIFY, AUDIT, and execution policy).
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
KERNEL_DIR = os.path.join(PROJECT_ROOT, "kernel")
LITE_FILES = ["ENTRY.md", "SOLVE.md", "VERIFY.md", "ESCALATE.md", "CLARIFY.md", "AUDIT.md", "POLICY.md"]

TOKEN_BUDGET = 7000

TARGETS = {
    "CLAUDE.md": {
        "title": "# DAI Nexus Kernel LITE — Claude Code",
        "description": "This file is read by Claude Code on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "AGENTS.md": {
        "title": "# DAI Nexus Kernel LITE — Antigravity / Cursor / Codex",
        "description": "This file is read by Antigravity / Cursor / Codex on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "GEMINI.md": {
        "title": "# DAI Nexus Kernel LITE — Gemini",
        "description": "This file is read by Gemini on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
}


def estimate_tokens(text):
    # Deterministic token estimation
    return len(text) // 4


def sync():
    print(f"Reading kernel files from: {KERNEL_DIR}")
    kernel_contents = []

    for filename in LITE_FILES:
        filepath = os.path.join(KERNEL_DIR, filename)
        if not os.path.exists(filepath):
            print(f"Error: Required kernel file '{filepath}' does not exist.")
            sys.exit(1)

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read().strip()
            # Clean up links to kernel files so agents don't try to reread them
            content = re.sub(r"\[kernel/([A-Z]+)\.md\]\([^)]+\)", r"\1 section", content)
            kernel_contents.append(content)

    combined_kernel = "\n\n".join(kernel_contents)
    print(f"Kernel source files estimate: {estimate_tokens(combined_kernel)} tokens")

    has_error = False
    for target_name, info in TARGETS.items():
        target_path = os.path.join(PROJECT_ROOT, target_name)

        content = f"""{info["title"]}

> **DO NOT EDIT THIS FILE DIRECTLY.** It is dynamically generated by the sync script.
> Source of truth resides in the `kernel/` directory. Run `python scripts/lite/sync-kernel.py` to regenerate.

{info["description"]}

---

{combined_kernel}
"""

        with open(target_path, "w", encoding="utf-8") as f:
            f.write(content)

        target_tokens = estimate_tokens(content)
        status = "OK" if target_tokens < TOKEN_BUDGET else "EXCEEDED LIMIT"
        print(f"Generated: {target_name} ({target_tokens} est. tokens) -> [{status}]")

        if target_tokens >= TOKEN_BUDGET:
            print(
                f"Error: {target_name} exceeds the {TOKEN_BUDGET} deterministic token budget limit!",
                file=sys.stderr,
            )
            has_error = True

    if has_error:
        sys.exit(1)


if __name__ == "__main__":
    sync()
