#!/usr/bin/env node
/**
 * dai-nexus — Global MCP Server
 * Works with ANY project - workspace determined by DAINEXUS_WORKSPACE env var
 * 
 * Auto-generated by DAI Nexus Global Setup
 */

import { startMCPServer } from "gitnexus/dist/mcp/server.js";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

// ─── Configuration ──────────────────────────────────────────────
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Workspace: Priority 1 = DAINEXUS_WORKSPACE env var
//            Priority 2 = computed from __dirname
const DAINEXUS_WORKSPACE = process.env.DAINEXUS_WORKSPACE;
const DAINEXUS_DIR = process.env.DAINEXUS_DIR || resolve(__dirname, "../..");

// Determine project root
let PROJECT_ROOT;
if (DAINEXUS_WORKSPACE) {
    PROJECT_ROOT = DAINEXUS_WORKSPACE;
} else {
    // Compute from __dirname: go up to project root
    // Path: .dainexus/mcp-server/ -> .dainexus/ -> project root
    PROJECT_ROOT = resolve(__dirname, "../..");
}

process.title = "dai-nexus-mcp";

console.error(`[DAI Nexus MCP] Starting with workspace: ${PROJECT_ROOT}`);
console.error(`[DAI Nexus MCP] DAI Nexus dir: ${DAINEXUS_DIR}`);

// ─── Start Native Server ────────────────────────────────────────

startMCPServer(PROJECT_ROOT).catch((err: any) => {
    console.error(`[DAI Nexus MCP] Fatal error: ${err.message}`);
    console.error(err.stack);
    process.exit(1);
});
